scan_timeout = 60
add_newline = true

[line_break]
disabled = false

#[directory]
#style = "bold blue"

[cmd_duration]
format = "took [$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[git_branch]
format = "on [$symbol$branch]($style) "

[package]
format = "is [$symbol$version]($style) "
symbol = " "

[python]
format = 'is [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "is [$symbol($version )]($style)"

[php]
format = "is [$symbol($version )]($style)"
symbol = " "

[java]
format = "is [${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "is [$symbol($version )]($style)"

[golang]
format = "is [$symbol($version )]($style)"
symbol = " "
